### ISSUE TITLE
FreeCodeCamp Quality_Assurance_and_Testing_with_Chai project cant run with full pass

### ISSUE THREAD

**Issue by screenleon** [screenleon/javascript#15]
TypeError: browser.fill(...).pressButton is not a function at Context.<anonymous> (tests/2_functional-tests.js:214:12)

TypeError: browser.fill(...).pressButton is not a function at Context.<anonymous> (tests/2_functional-tests.js:245:12)

TypeError: browser.fill(...).pressButton is not a function at Context.<anonymous> (tests/2_functional-tests.js:268:12)

**Comment by screenleon** [comment]
open issue on incorrect repository
